ProductApp : main.o person.o shop.o
	     g++ main.o person.o shop.o -o ProductApp

main.o : main.cpp
	 g++ -c main.cpp

person.o : person.cpp
	   g++ -c person.cpp

shop.o : shop.cpp
	 g++ -c shop.cpp

